# Generated by Django 4.2.7 on 2024-05-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='movie_type',
            field=models.TextField(),
        ),
    ]
