# Generated by Django 4.2.7 on 2024-05-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movietype_delete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietype',
            name='movie_type',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MovieDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duration_details', to='movie.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_duration', to='movie.movieduration'),
        ),
    ]
