# Generated by Django 4.2.7 on 2024-06-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
