# Generated by Django 4.2.7 on 2024-06-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_year',
            new_name='release_date',
        ),
    ]
